server {
  listen 80;

  gzip on;
  gzip_min_length 1k;
  gzip_buffers 4 16k;
  gzip_comp_level 8;
  gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
  gzip_vary off;
  gzip_static on;
  gzip_disable "MSIE [1-6].";

  client_max_body_size 5000m;

  location /ui/ {
    try_files $uri / /ui/index.html;
    alias /opt/lina/;
  }

  location /api/ {
    proxy_pass http://jms_fa_core:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /core/ {
    proxy_pass http://jms_fa_core:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /media/ {
    proxy_pass http://jms_fa_core:8080;
    proxy_set_header Host $host;
  }

  location /static/ {
    proxy_pass http://jms_fa_core:8080;
    proxy_set_header Host $host;
  }

  location /ws/ {
    proxy_pass http://jms_fa_core:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location / {
    rewrite ^/(.*)$ /ui/$1 last;
  }
}
